### ISSUE TITLE
Compiling with flang

### ISSUE THREAD

**Issue by tomneep** [BioFSILab/Bio-CFD#2]
Tried to compile with `flang 19.1.7` lots of errors such as 

```
error: Semantic errors in subNavierStokes.f90
./subNavierStokes.f90:1294:59: error: Actual argument for 'a=' has bad type or kind 'REAL(4)'
        block(g)%u(i,j-2,k))/(block(g)%ca6_vu(j)*ddye)+dabs(v_in_um)* &
```

because e.g. `v_in_um` defined as `REAL` without kind. Can fix by adding `kind=8` (but need to do proper fixing of all kinds anyway).

Alternatively, we probably should move from `dabs` to `abs` according to a quick check
